version: "3.8"

services:
  app:
    build: .
    container_name: image_server_app
    restart: unless-stopped
    volumes:
      - ./images:/app/images
      - ./static:/app/static
      - ./logs:/app/logs

    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Atyrau

  nginx:
    image: nginx:1.27
    container_name: image_server_nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
      - ./static:/app/static:ro
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  images:
  logs: